
name: Build & Deploy (Next export + MkDocs)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install & Build Next (frontend)
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install MkDocs Material
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material

      - name: Build MkDocs into /frontend/out/AppForge-Bench
        run: |
          mkdocs build --site-dir ./frontend/out/AppForge-Bench

      - name: Touch 404.html for GH Pages SPA routing
        working-directory: ./frontend/out
        run: |
          cp index.html 404.html

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/out
          force_orphan: true
